var h;h||=typeof Module !== 'undefined' ? Module : {};h.lg||(h.lg=0);h.lg++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,v){var r=new XMLHttpRequest;r.open("GET",n,!0);r.responseType="arraybuffer";r.onprogress=function(u){var B=p;u.total&&(B=u.total);if(u.loaded){r.$e?h.Cf[n].loaded=u.loaded:(r.$e=!0,h.Cf||(h.Cf={}),h.Cf[n]={loaded:u.loaded,total:B});var F=B=u=0,G;for(G in h.Cf){var N=h.Cf[G];u+=N.total;B+=N.loaded;F++}u=Math.ceil(u*h.lg/F);h.setStatus&&h.setStatus(`Downloading data... (${B}/${u})`)}else!h.Cf&&h.setStatus&&h.setStatus("Downloading data...")};
r.onerror=function(){throw Error("NetworkError for: "+n);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)v(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,B,F){this.start=u;this.end=B;this.audio=F}function p(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
u=new Uint8Array(u);n.prototype.If=u;u=a.files;for(var B=0;B<u.length;++B)n.prototype.$e[u[B].filename].onload();h.removeRunDependency("datafile_index.data")}n.prototype={$e:{},open:function(u,B){this.name=B;this.$e[B]=this;h.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.If.subarray(this.start,this.end))},finish:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency(`fp ${this.name}`);this.$e[this.name]=null}};for(var v=a.files,r=0;r<v.length;++r)(new n(v[r].start,
v[r].end,v[r].audio||0)).open("GET",v[r].filename);h.addRunDependency("datafile_index.data");h.Ng||(h.Ng={});h.Ng["index.data"]={Mh:!1};k?(p(k),k=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||
h.locateFile||(h.locateFile=h.locateFilePackage,aa("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("index.data",""):"index.data",f=a.remote_package_size,g=null,k=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;k||b(e,f,function(n){g?(g(n),g=null):k=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/MAIN.MIX",start:0,end:12687722},{filename:"/REDALERT.MIX",
start:12687722,end:24424418},{filename:"/redalert.ini",start:24424418,end:24425816}],remote_package_size:24425816});var ba=Object.assign({},h),ca=[],da="./this.program",ea=(a,b)=>{throw b;},ha="",ia,ja;"undefined"!=typeof document&&document.currentScript&&(ha=document.currentScript.src);ha=0!==ha.indexOf("blob:")?ha.substr(0,ha.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=h.print||console.log.bind(console),aa=h.printErr||console.error.bind(console);Object.assign(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);var la;h.wasmBinary&&(la=h.wasmBinary);"object"!=typeof WebAssembly&&l("no native wasm support detected");
var ma,na=!1,oa,m,q,pa,qa,t,w,x,y,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=h.preRun.shift();ra.unshift(a)}var xa=0,za=null,Aa=null;function Ba(){xa++;h.monitorRunDependencies&&h.monitorRunDependencies(xa)}function Ca(){xa--;h.monitorRunDependencies&&h.monitorRunDependencies(xa);if(0==xa&&(null!==za&&(clearInterval(za),za=null),Aa)){var a=Aa;Aa=null;a()}}
function l(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";aa(a);na=!0;oa=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Da=a=>a.startsWith("data:application/octet-stream;base64,"),Ea;Ea="index.wasm";if(!Da(Ea)){var Fa=Ea;Ea=h.locateFile?h.locateFile(Fa,ha):ha+Fa}function Ga(a){if(a==Ea&&la)return new Uint8Array(la);throw"both async and sync fetching of the wasm failed";}
function Ia(a){return la||"function"!=typeof fetch?Promise.resolve().then(()=>Ga(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ga(a))}function Ja(a,b,c){return Ia(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{aa(`failed to asynchronously prepare wasm: ${d}`);l(d)})}
function Ka(a,b){var c=Ea;la||"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||"function"!=typeof fetch?Ja(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){aa(`wasm streaming compile failed: ${e}`);aa("falling back to ArrayBuffer instantiation");return Ja(c,a,b)}))}
var z,A,Oa={167488:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,167635:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,167869:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.af||("undefined"!==typeof AudioContext?b.af=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.af=new webkitAudioContext),b.af&&
La(b.af));return void 0===b.af?-1:0},168362:()=>h.SDL2.af.sampleRate,168430:(a,b,c,d)=>{function e(){}function f(k){void 0!==g.capture.Of&&(clearTimeout(g.capture.Of),g.capture.Of=void 0);g.capture.Yf=g.af.createMediaStreamSource(k);g.capture.gf=g.af.createScriptProcessor(b,a,1);g.capture.gf.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.kg=n.inputBuffer,Ma(c,[d]))};g.capture.Yf.connect(g.capture.gf);g.capture.gf.connect(g.af.destination);
g.capture.stream=k}var g=h.SDL2;g.capture.dg=g.af.createBuffer(a,b,g.af.sampleRate);g.capture.dg.getChannelData(0).fill(0);g.capture.Of=setTimeout(function(){g.capture.kg=g.capture.dg;Ma(c,[d])},b/g.af.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},170082:(a,b,c,d)=>{var e=h.SDL2;e.audio.gf=
e.af.createScriptProcessor(b,0,a);e.audio.gf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Ag=f.outputBuffer,Ma(c,[d]))};e.audio.gf.connect(e.af.destination)},170492:(a,b)=>{for(var c=h.SDL2,d=c.capture.kg.numberOfChannels,e=0;e<d;++e){var f=c.capture.kg.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Na(a+4*g,f[g]);else for(g=0;g<b;++g)Na(a+4*(g*d+e),
f[g])}},171097:(a,b)=>{for(var c=h.SDL2,d=c.audio.Ag.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ag.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>2]}},171577:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Of&&clearTimeout(b.capture.Of);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.gf&&(b.capture.gf.onaudioprocess=function(){},b.capture.gf.disconnect(),b.capture.gf=void 0);void 0!==b.capture.Yf&&(b.capture.Yf.disconnect(),b.capture.Yf=void 0);void 0!==b.capture.dg&&(b.capture.dg=void 0);b.capture=void 0}else void 0!=b.audio.gf&&(b.audio.gf.disconnect(),b.audio.gf=void 0),b.audio=void 0;void 0!==b.af&&void 0===b.audio&&void 0===b.capture&&(b.af.close(),b.af=void 0)},172749:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Yg!==h.canvas&&
(d.rf=h.createContext(h.canvas,!1,!0),d.Yg=h.canvas);if(d.w!==a||d.h!==b||d.kh!==d.rf)d.image=d.rf.createImageData(a,b),d.w=a,d.h=b,d.kh=d.rf;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=t[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.ah!==a&&(d.$g=new Int32Array(a.buffer),d.bh=new Uint8Array(a.buffer),d.ah=a),a=d.$g,c=a.length,a.set(t.subarray(b,b+c)),a=d.bh,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.rf.putImageData(d.image,0,0)},174218:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var k=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;k<n;){var p=t[e];b[k]=p&255;b[k+1]=p>>8&255;b[k+2]=p>>16&
255;b[k+3]=p>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(t.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=C(c.length+1);D(c,q,d,c.length+1);return d},175207:a=>{h.canvas&&(h.canvas.style.cursor=a?E(q,a):"")},175290:()=>{h.canvas&&(h.canvas.style.cursor="none")},175359:()=>window.innerWidth,175389:()=>window.innerHeight};
function Ra(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Sa=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},La=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Sa(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ta=a=>{for(;0<a.length;)a.shift()(h)},Ma=(a,b)=>{var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)},Ua=h.noExitRuntime||!0;
function Na(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a>>0]=b;break;case "i8":m[a>>0]=b;break;case "i16":pa[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":l("to do setValue(i64) use WASM_BIGINT");case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;case "*":w[a>>2]=b;break;default:l(`invalid type for setValue: ${c}`)}}
function Va(a){this.$f=a-24;this.Sg=function(b){w[this.$f+4>>2]=b};this.hg=function(b){w[this.$f+8>>2]=b};this.$e=function(b,c){this.If();this.Sg(b);this.hg(c)};this.If=function(){w[this.$f+16>>2]=0}}
var Wa=0,Xa=0,Ya=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Za=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ya(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},$a=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},
ab=a=>{if("/"===a)return"/";a=Za(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},bb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);l("initRandomDevice")},cb=a=>(cb=bb())(a);
function db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ya(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var eb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&eb)return eb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
fb=[],gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function hb(a){var b=Array(gb(a)+1);a=D(a,b,0,b.length);b.length=a;return b}var ib=[];function jb(a,b){ib[a]={input:[],ff:[],wf:b};lb(a,mb)}
var mb={open(a){var b=ib[a.node.Mf];if(!b)throw new H(43);a.Ve=b;a.seekable=!1},close(a){a.Ve.wf.Uf(a.Ve)},Uf(a){a.Ve.wf.Uf(a.Ve)},read(a,b,c,d){if(!a.Ve||!a.Ve.wf.Cg)throw new H(60);for(var e=0,f=0;f<d;f++){try{var g=a.Ve.wf.Cg(a.Ve)}catch(k){throw new H(29);}if(void 0===g&&0===e)throw new H(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Ve||!a.Ve.wf.pg)throw new H(60);try{for(var e=0;e<d;e++)a.Ve.wf.pg(a.Ve,b[c+e])}catch(f){throw new H(29);
}d&&(a.node.timestamp=Date.now());return e}},nb={Cg(){a:{if(!fb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}fb=hb(a)}a=fb.shift()}return a},pg(a,b){null===b||10===b?(ka(E(a.ff,0)),a.ff=[]):0!=b&&a.ff.push(b)},Uf(a){a.ff&&0<a.ff.length&&(ka(E(a.ff,0)),a.ff=[])},nh(){return{Gh:25856,Ih:5,Fh:191,Hh:35387,Eh:[3,28,127,21,4,0,1,0,17,
19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},oh(){return 0},ph(){return[24,80]}},ob={pg(a,b){null===b||10===b?(aa(E(a.ff,0)),a.ff=[]):0!=b&&a.ff.push(b)},Uf(a){a.ff&&0<a.ff.length&&(aa(E(a.ff,0)),a.ff=[])}};function pb(a,b){var c=a.Se?a.Se.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Se,a.Se=new Uint8Array(b),0<a.Ye&&a.Se.set(c.subarray(0,a.Ye),0))}
var I={tf:null,vf(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.tf||(I.tf={dir:{node:{sf:I.Re.sf,lf:I.Re.lf,Lf:I.Re.Lf,Zf:I.Re.Zf,Og:I.Re.Og,gg:I.Re.gg,cg:I.Re.cg,ag:I.Re.ag,fg:I.Re.fg},stream:{Af:I.Te.Af}},file:{node:{sf:I.Re.sf,lf:I.Re.lf},stream:{Af:I.Te.Af,read:I.Te.read,write:I.Te.write,wg:I.Te.wg,og:I.Te.og,Kg:I.Te.Kg}},link:{node:{sf:I.Re.sf,lf:I.Re.lf,Nf:I.Re.Nf},stream:{}},zg:{node:{sf:I.Re.sf,lf:I.Re.lf},stream:qb}});
c=rb(a,b,c,d);K(c.mode)?(c.Re=I.tf.dir.node,c.Te=I.tf.dir.stream,c.Se={}):32768===(c.mode&61440)?(c.Re=I.tf.file.node,c.Te=I.tf.file.stream,c.Ye=0,c.Se=null):40960===(c.mode&61440)?(c.Re=I.tf.link.node,c.Te=I.tf.link.stream):8192===(c.mode&61440)&&(c.Re=I.tf.zg.node,c.Te=I.tf.zg.stream);c.timestamp=Date.now();a&&(a.Se[b]=c,a.timestamp=c.timestamp);return c},Oh(a){return a.Se?a.Se.subarray?a.Se.subarray(0,a.Ye):new Uint8Array(a.Se):new Uint8Array(0)},Re:{sf(a){var b={};b.eh=8192===(a.mode&61440)?a.id:
1;b.Eg=a.id;b.mode=a.mode;b.th=1;b.uid=0;b.ih=0;b.Mf=a.Mf;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ye:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ug=new Date(a.timestamp);b.sh=new Date(a.timestamp);b.Xg=new Date(a.timestamp);b.Vg=4096;b.Wg=Math.ceil(b.size/b.Vg);return b},lf(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ye!=b))if(0==b)a.Se=null,a.Ye=0;else{var c=a.Se;a.Se=new Uint8Array(b);c&&a.Se.set(c.subarray(0,
Math.min(b,a.Ye)));a.Ye=b}},Lf(){throw sb[44];},Zf(a,b,c,d){return I.createNode(a,b,c,d)},Og(a,b,c){if(K(a.mode)){try{var d=tb(b,c)}catch(f){}if(d)for(var e in d.Se)throw new H(55);}delete a.parent.Se[a.name];a.parent.timestamp=Date.now();a.name=c;b.Se[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},gg(a,b){delete a.Se[b];a.timestamp=Date.now()},cg(a,b){var c=tb(a,b),d;for(d in c.Se)throw new H(55);delete a.Se[b];a.timestamp=Date.now()},ag(a){var b=[".",".."],c;for(c in a.Se)a.Se.hasOwnProperty(c)&&
b.push(c);return b},fg(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},Nf(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},Te:{read(a,b,c,d,e){var f=a.node.Se;if(e>=a.node.Ye)return 0;a=Math.min(a.node.Ye-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Se||a.Se.subarray)){if(f)return a.Se=b.subarray(c,c+d),a.Ye=d;if(0===a.Ye&&0===e)return a.Se=b.slice(c,
c+d),a.Ye=d;if(e+d<=a.Ye)return a.Se.set(b.subarray(c,c+d),e),d}pb(a,e+d);if(a.Se.subarray&&b.subarray)a.Se.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Se[e+f]=b[c+f];a.Ye=Math.max(a.Ye,e+d);return d},Af(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ye);if(0>b)throw new H(28);return b},wg(a,b,c){pb(a.node,b+c);a.node.Ye=Math.max(a.node.Ye,b+c)},og(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.Se;if(e&2||a.buffer!==m.buffer){if(0<c||c+b<a.length)a.subarray?
a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;l();b=void 0;if(!b)throw new H(48);m.set(a,b)}else c=!1,b=a.byteOffset;return{$f:b,Ah:c}},Kg(a,b,c,d){I.Te.write(a,b,0,d,c,!1);return 0}}},ub=(a,b,c)=>{var d=`al ${a}`;ja(a,e=>{e||l(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ca(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ba(d)},vb=h.preloadPlugins||[],yb=(a,b,c,d)=>{"undefined"!=typeof wb&&xb();var e=!1;vb.forEach(f=>{!e&&f.canHandle(b)&&
(f.handle(a,b,c,d),e=!0)});return e},Ab=(a,b,c,d,e,f,g,k,n,p)=>{function v(B){function F(G){p&&p();k||zb(a,b,G,d,e,n);f&&f();Ca(u)}yb(B,r,F,()=>{g&&g();Ca(u)})||F(B)}var r=b?db(Za(a+"/"+b)):a,u=`cp ${r}`;Ba(u);"string"==typeof c?ub(c,B=>v(B),g):v(c)},Bb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Cb=null,Db={},Eb=[],Fb=1,Gb=null,Hb=!0,H=null,sb={};
function L(a,b={}){a=db(a);if(!a)return{path:"",node:null};b=Object.assign({Bg:!0,qg:0},b);if(8<b.qg)throw new H(32);a=a.split("/").filter(g=>!!g);for(var c=Cb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=tb(c,a[e]);d=Za(d+"/"+a[e]);c.Df&&(!f||f&&b.Bg)&&(c=c.Df.root);if(!f||b.Kf)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=db($a(d),c),c=L(d,{qg:b.qg+1}).node,40<f++)throw new H(32);}return{path:d,node:c}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.vf.Jg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Lb(a){var b=Kb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.Ef;else for(b=Gb[b];b;){if(b.Ef===a){b.Ef=a.Ef;break}b=b.Ef}}
function tb(a,b){var c;if(c=(c=Mb(a,"x"))?c:a.Re.Lf?0:2)throw new H(c,a);for(c=Gb[Kb(a.id,b)];c;c=c.Ef){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Re.Lf(a,b)}function rb(a,b,c,d){a=new Nb(a,b,c,d);b=Kb(a.parent.id,a.name);a.Ef=Gb[b];return Gb[b]=a}function K(a){return 16384===(a&61440)}function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Mb(a,b){if(Hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Pb(a,b){try{return tb(a,b),20}catch(c){}return Mb(a,"wx")}function Qb(a,b,c){try{var d=tb(a,b)}catch(e){return e.df}if(a=Mb(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(d===d.parent||"/"===Jb(d))return 10}else if(K(d.mode))return 31;return 0}function Rb(){for(var a=0;4096>=a;a++)if(!Eb[a])return a;throw new H(33);}
function Sb(a){a=Eb[a];if(!a)throw new H(8);return a}function Tb(a,b=-1){Ub||(Ub=function(){this.$e={}},Ub.prototype={},Object.defineProperties(Ub.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.$e.flags},set(c){this.$e.flags=c}},position:{get(){return this.$e.position},set(c){this.$e.position=c}}}));a=Object.assign(new Ub,a);-1==b&&(b=Rb());a.fd=b;return Eb[b]=a}var qb={open(a){a.Te=Db[a.node.Mf].Te;a.Te.open&&a.Te.open(a)},Af(){throw new H(70);}};
function lb(a,b){Db[a]={Te:b}}function Vb(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new H(10);if(!c&&!d){var e=L(b,{Bg:!1});b=e.path;e=e.node;if(e.Df)throw new H(10);if(!K(e.mode))throw new H(54);}b={type:a,Uh:{},Jg:b,rh:[]};a=a.vf(b);a.vf=b;b.root=a;c?Cb=a:e&&(e.Df=b,e.vf&&e.vf.rh.push(b))}function Wb(a,b,c){var d=L(a,{parent:!0}).node;a=ab(a);if(!a||"."===a||".."===a)throw new H(28);var e=Pb(d,a);if(e)throw new H(e);if(!d.Re.Zf)throw new H(63);return d.Re.Zf(d,a,b,c)}
function Xb(a,b){return Wb(a,(void 0!==b?b:511)&1023|16384,0)}function Yb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Wb(a,b|8192,c)}function Zb(a,b){if(!db(a))throw new H(44);var c=L(b,{parent:!0}).node;if(!c)throw new H(44);b=ab(b);var d=Pb(c,b);if(d)throw new H(d);if(!c.Re.fg)throw new H(63);c.Re.fg(c,b,a)}
function $b(a){var b=L(a,{parent:!0}).node;if(!b)throw new H(44);a=ab(a);var c=tb(b,a),d=Qb(b,a,!1);if(d)throw new H(d);if(!b.Re.gg)throw new H(63);if(c.Df)throw new H(10);b.Re.gg(b,a);Lb(c)}function Ib(a){a=L(a).node;if(!a)throw new H(44);if(!a.Re.Nf)throw new H(28);return db(Jb(a.parent),a.Re.Nf(a))}function ac(a,b){a="string"==typeof a?L(a,{Kf:!0}).node:a;if(!a.Re.lf)throw new H(63);a.Re.lf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function bc(a,b,c){if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Za(a);try{e=L(a,{Kf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Wb(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!K(e.mode))throw new H(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:K(e.mode)&&("r"!==Ob(b)||b&512)?31:Mb(e,Ob(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?L(c,{Kf:!0}).node:c;if(!c.Re.lf)throw new H(63);if(K(c.mode))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=Mb(c,"w"))throw new H(d);c.Re.lf(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Tb({node:e,path:Jb(e),flags:b,seekable:!0,position:0,Te:e.Te,xh:[],error:!1});e.Te.open&&e.Te.open(e);!h.logReadFiles||b&1||(cc||={},a in cc||(cc[a]=1));return e}
function dc(a){if(null===a.fd)throw new H(8);a.zf&&(a.zf=null);try{a.Te.close&&a.Te.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null}function ec(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.Te.Af)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.Te.Af(a,b,c);a.xh=[];return a.position}
function fc(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(K(a.node.mode))throw new H(31);if(!a.Te.write)throw new H(28);a.seekable&&a.flags&1024&&ec(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H(70);b=a.Te.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function gc(){H||(H=function(a,b){this.name="ErrnoError";this.node=b;this.vh=function(c){this.df=c};this.vh(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{sb[a]=new H(a);sb[a].stack="<generic error, no stack>"}))}var hc;function ic(a,b){a="string"==typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Za(a+"/"+c);try{Xb(d)}catch(e){}a=d}}return d}
function jc(a,b,c,d){a=Za(("string"==typeof a?a:Jb(a))+"/"+b);c=Bb(c,d);return Wb(a,(void 0!==c?c:438)&4095|32768,0)}function zb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Jb(a),g=b?Za(a+"/"+b):a);a=Bb(d,e);g=Wb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}ac(g,a|146);b=bc(g,577);fc(b,c,0,c.length,0,f);dc(b);ac(g,a)}}
function kc(a,b,c,d){a=Za(("string"==typeof a?a:Jb(a))+"/"+b);b=Bb(!!c,!!d);kc.Hg||(kc.Hg=64);var e=kc.Hg++<<8|0;lb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,g,k,n){for(var p=0,v=0;v<n;v++){try{var r=c()}catch(u){throw new H(29);}if(void 0===r&&0===p)throw new H(6);if(null===r||void 0===r)break;p++;g[k+v]=r}p&&(f.node.timestamp=Date.now());return p},write(f,g,k,n){for(var p=0;p<n;p++)try{d(g[k+p])}catch(v){throw new H(29);}n&&(f.node.timestamp=Date.now());return p}});
return Yb(a,b,e)}function lc(a){if(!(a.Gg||a.qh||a.link||a.Se)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.Se=hb(ia(a.url)),a.Ye=a.Se.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function mc(a,b,c,d,e){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Gg:!1,url:c};var f=jc(a,b,d,e);c.Se?f.Se=c.Se:c.url&&(f.Se=null,f.url=c.url);Object.defineProperties(f,{Ye:{get:function(){return this.Se.length}}});var g={};Object.keys(f.Te).forEach(k=>{var n=f.Te[k];g[k]=function(){lc(f);return n.apply(null,arguments)}});g.read=(k,n,p,v,r)=>{lc(f);k=k.node.Se;if(r>=k.length)n=
0;else{v=Math.min(k.length-r,v);if(k.slice)for(var u=0;u<v;u++)n[p+u]=k[r+u];else for(u=0;u<v;u++)n[p+u]=k.get(r+u);n=v}return n};g.og=()=>{lc(f);l();throw new H(48);};f.Te=g;return f}var nc={},Ub,cc;function oc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Sb(a).path;if(0==b.length)throw new H(44);return Za(a+"/"+b)}var pc=void 0;function qc(){var a=t[+pc>>2];pc+=4;return a}
var Bc=(a,b)=>{rc=a;sc=b;if(tc)if(uc||=!0,0==a)vc=function(){var d=Math.max(0,wc+b-xc())|0;setTimeout(yc,d)};else if(1==a)vc=function(){zc(yc)};else if(2==a){if("undefined"==typeof Ac)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ac=function(d){c.push(d);postMessage("setimmediate","*")}}else Ac=setImmediate;vc=function(){Ac(yc)}}},xc;xc=()=>performance.now();
var Ic=a=>{!tc||l("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");tc=a;var b=Cc;uc=!1;yc=function(){if(!na)if(0<Dc.length){var c=Dc.shift();c.Nh(c.Bh);if(Ec){var d=Ec,e=0==d%1?d-1:Math.floor(d);Ec=c.Kh?e:(8*d+(e+.5))/9}h.setStatus&&(c=h.statusMessage||"Please wait...",d=Ec,e=Fc.Lh,d?d<e?h.setStatus(c+" ("+(e-d)+"/"+e+")"):h.setStatus(c):h.setStatus(""));b<
Cc||setTimeout(yc,0)}else b<Cc||(Gc=Gc+1|0,1==rc&&1<sc&&0!=Gc%sc?vc():(0==rc&&(wc=xc()),na||h.preMainLoop&&!1===h.preMainLoop()||(Hc(a),h.postMainLoop&&h.postMainLoop()),b<Cc||("object"==typeof SDL&&SDL.audio&&SDL.audio.uh&&SDL.audio.uh(),vc())))}},Jc=a=>{a instanceof Ra||"unwind"==a||ea(1,a)},Kc=a=>{oa=a;if(!Ua){if(h.onExit)h.onExit(a);na=!0}ea(a,new Ra(a))},Lc=a=>{oa=a;Kc(a)},Hc=a=>{if(!na)try{if(a(),!Ua)try{oa=a=oa,Kc(a)}catch(b){Jc(b)}}catch(b){Jc(b)}},Mc=(a,b)=>setTimeout(()=>{Hc(a)},b),uc=!1,
vc=null,Cc=0,tc=null,rc=0,sc=0,Gc=0,Dc=[];function Nc(){vc=null;Cc++}function Oc(){Cc++;var a=rc,b=sc,c=tc;tc=null;Ic(c);Bc(a,b);vc()}var Fc={},wc,yc,Ec,Pc=!1,Qc=!1,Rc=[];
function xb(){function a(){Qc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Sc){Sc=!0;vb.push({canHandle:function(c){return!h.Th&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Tc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Tc(d)}));var k=URL.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||l(`Image ${d} could not be decoded`);
var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(k);e&&e(c)};n.onerror=()=>{aa(`Image ${k} could not be decoded`);f&&f()};n.src=k}});vb.push({canHandle:function(c){return!h.Sh&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e&&e(c))}var g=!1,k=URL.createObjectURL(new Blob([c],{type:Tc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){aa(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",v=0,r=0,u=0;u<c.length;u++)for(v=v<<8|c[u],r+=8;6<=r;){var B=v>>r-6&63;r-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==r?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],p+="=="):4==r&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=k;Mc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Qc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Uc=!1,Vc=void 0,Wc=void 0;function Xc(){if(!Pc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Yc=0;
function zc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Yc)Yc=b+1E3/60;else for(;b+2>=Yc;)Yc+=1E3/60;setTimeout(a,Math.max(Yc-b,0))}}function Tc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Zc=[];function $c(){var a=h.canvas;Zc.forEach(b=>b(a.width,a.height))}
function ad(a,b,c){b&&c?(a.zh=b,a.jh=c):(b=a.zh,c=a.jh);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Wc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var wb={},Ac,Sc,bd={},cd={},M=null,O={0:{id:0,Bf:0,We:null,frequency:0,jf:2,channels:1,length:0}},dd=1,ed=[],gd=a=>{if((1!==rc||"visible"==document.visibilityState)&&4114===a.state){for(var b=fd(a),c=a.cf,d=a.bf,e=a.Ue,f=0;f<a.Ze.length;f++){var g=a.Ze[f];c=g.Sf+g.Gf;d=0;e+=g.vg+1}k||=.1;var k=b+k;for(b=0;c<k;){if(e>=a.Wd.length)if(a.kf)e%=a.Wd.length;else break;f=a.Wd[e%a.Wd.length];if(0===f.length){if(b++,b===a.Wd.length)break}else{g=a.context.hf.createBufferSource();g.buffer=f.We;g.playbackRate.value=
a.playbackRate;if(f.We.Rf||f.We.Qf)g.loopStart=f.We.Rf,g.loopEnd=f.We.Qf;if(4136===a.type&&a.kf){var n=Number.POSITIVE_INFINITY;g.loop=!0;f.We.Rf&&(g.loopStart=f.We.Rf);f.We.Qf&&(g.loopEnd=f.We.Qf)}else n=(f.We.duration-d)/a.playbackRate;g.Tg=d;g.Gf=n;g.vg=b;b=0;g.connect(a.gain);"undefined"!=typeof g.start?(c=Math.max(c,a.context.hf.currentTime),g.start(c,d)):"undefined"!=typeof g.noteOn&&(c=Math.max(c,a.context.hf.currentTime),g.noteOn(c));g.Sf=c;a.Ze.push(g);c+=n}d=0;e++}}},fd=a=>{var b=a.context.hf.currentTime;
if(4114!==a.state)return b;isFinite(a.cf)||(a.cf=b-a.bf/a.playbackRate,a.bf=0);for(var c;a.Ze.length;){c=a.Ze[0];a.Ue+=c.vg;c=c.Sf+c.Gf;if(b<c)break;a.Ze.shift();a.cf=c;a.bf=0;a.Ue++}if(a.Ue>=a.Wd.length&&!a.kf)hd(a,4116);else if(4136===a.type&&a.kf)if(c=a.Wd[0],0===c.length)a.bf=0;else{var d=(b-a.cf)*a.playbackRate,e=c.We.Rf||0,f=c.We.Qf||c.We.duration;f<=e&&(f=c.We.duration);d<f?a.bf=d:a.bf=e+(d-e)%(f-e)}else if(a.Ze[0])a.bf=(b-a.Ze[0].Sf)*a.playbackRate;else for(4136!==a.type&&a.kf&&(c=jd(a)/a.playbackRate,
0<c&&(a.cf+=Math.floor((b-a.cf)/c)*c)),d=0;d<a.Wd.length;d++){if(a.Ue>=a.Wd.length)if(a.kf)a.Ue%=a.Wd.length;else{hd(a,4116);break}c=a.Wd[a.Ue];if(0<c.length){c=a.cf+c.We.duration/a.playbackRate;if(b<c){a.bf=(b-a.cf)*a.playbackRate;break}a.cf=c}a.bf=0;a.Ue++}return b},kd=a=>{fd(a);for(var b=1;b<a.Ze.length;b++)a.Ze[b].stop();1<a.Ze.length&&(a.Ze.length=1)},ld=a=>{for(var b=0;b<a.Ze.length;b++)a.Ze[b].stop();a.Ze.length=0},hd=(a,b)=>{if(4114===b){if(4114===a.state||4116==a.state)a.Ue=0,a.bf=0;ld(a);
a.state=4114;a.cf=Number.NEGATIVE_INFINITY;gd(a)}else 4115===b?4114===a.state&&(fd(a),ld(a),a.state=4115):4116===b?4113!==a.state&&(a.state=4116,a.Ue=a.Wd.length,a.cf=Number.NEGATIVE_INFINITY,a.bf=0,ld(a)):4113===b&&4113!==a.state&&(a.state=4113,a.Ue=0,a.cf=Number.NEGATIVE_INFINITY,a.bf=0,ld(a))},od=a=>{if(4144!==a.type){for(var b=O[0],c=0;c<a.Wd.length;c++)if(0!==a.Wd[c].id){b=a.Wd[c];break}1===a.eg||2===a.eg&&1===b.channels?a.Xe||(a.Xe=a.context.hf.createPanner(),md(a),nd(a),a.Xe.connect(a.context.gain),
a.gain.disconnect(),a.gain.connect(a.Xe)):a.Xe&&(a.Xe.disconnect(),a.gain.disconnect(),a.gain.connect(a.context.gain),a.Xe=null)}},pd=a=>{for(var b in a.sources)md(a.sources[b])},md=a=>{var b=a.Xe;if(b)switch(b.refDistance=a.refDistance,b.maxDistance=a.maxDistance,b.rolloffFactor=a.rolloffFactor,b.panningModel=a.context.Dg?"HRTF":"equalpower",a.context.Pg?a.distanceModel:a.context.distanceModel){case 0:b.distanceModel="inverse";b.refDistance=3.40282E38;break;case 53249:case 53250:b.distanceModel=
"inverse";break;case 53251:case 53252:b.distanceModel="linear";break;case 53253:case 53254:b.distanceModel="exponential"}},nd=a=>{if(a.Xe){var b=a.Xe,c=a.position[0],d=a.position[1],e=a.position[2],f=a.direction[0],g=a.direction[1],k=a.direction[2],n=a.context.listener,p=n.position[0],v=n.position[1],r=n.position[2];if(a.bg){var u=-n.direction[0],B=-n.direction[1],F=-n.direction[2],G=n.ug[0],N=n.ug[1],fa=n.ug[2],P=(kb,Yd,Zd)=>{kb=Math.sqrt(kb*kb+Yd*Yd+Zd*Zd);return kb<Number.EPSILON?0:1/kb},J=P(u,
B,F);u*=J;B*=J;F*=J;J=P(G,N,fa);G*=J;N*=J;fa*=J;var ya=N*F-fa*B,Pa=fa*u-G*F,Qa=G*B-N*u;J=P(ya,Pa,Qa);ya*=J;Pa*=J;Qa*=J;G=B*Qa-F*Pa;N=F*ya-u*Qa;fa=u*Pa-B*ya;P=f;J=g;var Ha=k;f=P*ya+J*G+Ha*u;g=P*Pa+J*N+Ha*B;k=P*Qa+J*fa+Ha*F;P=c;J=d;Ha=e;c=P*ya+J*G+Ha*u+p;d=P*Pa+J*N+Ha*B+v;e=P*Qa+J*fa+Ha*F+r}b.positionX?(c!=b.positionX.value&&(b.positionX.value=c),d!=b.positionY.value&&(b.positionY.value=d),e!=b.positionZ.value&&(b.positionZ.value=e)):b.setPosition(c,d,e);b.orientationX?(f!=b.orientationX.value&&(b.orientationX.value=
f),g!=b.orientationY.value&&(b.orientationY.value=g),k!=b.orientationZ.value&&(b.orientationZ.value=k)):b.setOrientation(f,g,k);b=a.Jf;f=a.qf[0];g=a.qf[1];k=a.qf[2];u=n.qf[0];B=n.qf[1];n=n.qf[2];c===p&&d===v&&e===r||f===u&&g===B&&k===n?a.Jf=1:(F=a.context.speedOfSound,G=a.context.dopplerFactor,c=p-c,d=v-d,e=r-e,r=Math.sqrt(c*c+d*d+e*e),a.Jf=(F-G*Math.min((c*u+d*B+e*n)/r,F/G))/(F-G*Math.min((c*f+d*g+e*k)/r,F/G)));a.Jf!==b&&qd(a)}},qd=a=>{if(4114===a.state){kd(a);var b=a.Ze[0];b&&(b.Gf=4136===a.type&&
a.kf?Number.POSITIVE_INFINITY:(b.buffer.duration-b.Tg)/a.playbackRate,b.playbackRate.value=a.playbackRate,gd(a))}},jd=a=>{for(var b=0,c=0;c<a.Wd.length;c++){var d=a.Wd[c].We;b+=d?d.duration:0}return b},rd=a=>{fd(a);for(var b=0,c=0;c<a.Ue;c++)a.Wd[c].We&&(b+=a.Wd[c].We.duration);return b+=a.bf},sd=(a,b)=>{var c=4114==a.state;c&&hd(a,4113);if(null!==a.Wd[a.Ue].We){for(a.Ue=0;b>a.Wd[a.Ue].We.duration;)b-=a.Wd[a.Ue].Dh.duration,a.Ue++;a.bf=b}c&&hd(a,4114)},td=(a,b)=>{if(!M)return null;a=M.sources[a];
if(!a)return M.ce=40961,null;switch(b){case 514:return a.bg;case 4097:return a.coneInnerAngle;case 4098:return a.coneOuterAngle;case 4099:return a.pitch;case 4100:return a.position;case 4101:return a.direction;case 4102:return a.qf;case 4103:return a.kf;case 4105:return 4136===a.type?a.Wd[0].id:0;case 4106:return a.gain.gain.value;case 4109:return a.ng;case 4110:return a.mg;case 4112:return a.state;case 4117:return 1===a.Wd.length&&0===a.Wd[0].id?0:a.Wd.length;case 4118:return 1===a.Wd.length&&0===
a.Wd[0].id||a.kf?0:a.Ue;case 4128:return a.refDistance;case 4129:return a.rolloffFactor;case 4130:return a.coneOuterGain;case 4131:return a.maxDistance;case 4132:return rd(a);case 4133:return b=rd(a),0<b&&(b*=a.Wd[0].frequency),b;case 4134:return b=rd(a),0<b&&(b*=a.Wd[0].frequency*a.Wd[0].jf),b;case 4135:return a.type;case 4628:return a.eg;case 8201:for(var c=b=0,d=0;d<a.Wd.length;d++)b+=a.Wd[d].length,0!==a.Wd[d].id&&(c=a.Wd[d].jf*a.Wd[d].channels);return b*c;case 8202:for(d=b=0;d<a.Wd.length;d++)b+=
a.Wd[d].length;return b;case 8203:return jd(a);case 53248:return a.distanceModel;default:return M.ce=40962,null}},ud=(a,b,c)=>{if(M)if(a=M.sources[a])if(null===c)M.ce=40962;else switch(b){case 514:1===c?(a.bg=!0,nd(a)):0===c?(a.bg=!1,nd(a)):M.ce=40963;break;case 4097:if(!Number.isFinite(c)){M.ce=40963;break}a.coneInnerAngle=c;a.Xe&&(a.Xe.coneInnerAngle=c%360);break;case 4098:if(!Number.isFinite(c)){M.ce=40963;break}a.coneOuterAngle=c;a.Xe&&(a.Xe.coneOuterAngle=c%360);break;case 4099:if(!Number.isFinite(c)||
0>=c){M.ce=40963;break}if(a.pitch===c)break;a.pitch=c;qd(a);break;case 4100:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){M.ce=40963;break}a.position[0]=c[0];a.position[1]=c[1];a.position[2]=c[2];nd(a);break;case 4101:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){M.ce=40963;break}a.direction[0]=c[0];a.direction[1]=c[1];a.direction[2]=c[2];nd(a);break;case 4102:if(!Number.isFinite(c[0])||!Number.isFinite(c[1])||!Number.isFinite(c[2])){M.ce=
40963;break}a.qf[0]=c[0];a.qf[1]=c[1];a.qf[2]=c[2];nd(a);break;case 4103:if(1===c)a.kf=!0,fd(a),4136===a.type&&0<a.Ze.length&&(c=a.Ze[0],c.loop=!0,c.Gf=Number.POSITIVE_INFINITY);else if(0===c){a.kf=!1;var d=fd(a);4136===a.type&&0<a.Ze.length&&(c=a.Ze[0],c.loop=!1,c.Gf=a.Wd[0].We.duration/a.playbackRate,c.Sf=d-a.bf/a.playbackRate)}else M.ce=40963;break;case 4105:if(4114===a.state||4115===a.state){M.ce=40964;break}if(0===c){for(d in a.Wd)a.Wd[d].Bf--;a.Wd.length=1;a.Wd[0]=O[0];a.Ue=0;a.type=4144}else{var e=
O[c];if(!e){M.ce=40963;break}for(d in a.Wd)a.Wd[d].Bf--;a.Wd.length=0;e.Bf++;a.Wd=[e];a.Ue=0;a.type=4136}od(a);gd(a);break;case 4106:if(!Number.isFinite(c)||0>c){M.ce=40963;break}a.gain.gain.value=c;break;case 4109:if(!Number.isFinite(c)||0>c||c>Math.min(a.mg,1)){M.ce=40963;break}a.ng=c;break;case 4110:if(!Number.isFinite(c)||c<Math.max(0,a.ng)||1<c){M.ce=40963;break}a.mg=c;break;case 4128:if(!Number.isFinite(c)||0>c){M.ce=40963;break}a.refDistance=c;a.Xe&&(a.Xe.refDistance=c);break;case 4129:if(!Number.isFinite(c)||
0>c){M.ce=40963;break}a.rolloffFactor=c;a.Xe&&(a.Xe.rolloffFactor=c);break;case 4130:if(!Number.isFinite(c)||0>c||1<c){M.ce=40963;break}a.coneOuterGain=c;a.Xe&&(a.Xe.coneOuterGain=c);break;case 4131:if(!Number.isFinite(c)||0>c){M.ce=40963;break}a.maxDistance=c;a.Xe&&(a.Xe.maxDistance=c);break;case 4132:if(0>c||c>jd(a)){M.ce=40963;break}sd(a,c);break;case 4133:d=jd(a);if(0<d){for(var f in a.Wd)if(f){e=a.Wd[f].frequency;break}c/=e}if(0>c||c>d){M.ce=40963;break}sd(a,c);break;case 4134:d=jd(a);if(0<d){for(f in a.Wd)if(f){e=
a.Wd[f];var g=e.frequency*e.jf*e.channels;break}c/=g}if(0>c||c>d){M.ce=40963;break}sd(a,c);break;case 4628:if(0!==c&&1!==c&&2!==c){M.ce=40963;break}a.eg=c;od(a);break;case 8201:case 8202:case 8203:M.ce=40964;break;case 53248:switch(c){case 0:case 53249:case 53250:case 53251:case 53252:case 53253:case 53254:a.distanceModel=c;M.Pg&&pd(M);break;default:M.ce=40963}break;default:M.ce=40962}else M.ce=40961},Q=12288,vd=!1,wd=0,xd=0,yd=0,R={alpha:!1,depth:!1,stencil:!1,antialias:!1},zd={},Ad,Bd=a=>{var b=
a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Cd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Dd=
a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ed=1,Fd=[],S=[],Gd=[],Hd=[],Id=[],T=[],Jd=[],Kd=[],Ld=[],Md={},Nd=4;function U(a){Od||=a}
var Pd=a=>{for(var b=Ed++,c=a.length;c<b;c++)a[c]=null;return b},Rd=(a,b)=>{a.$e||(a.$e=a.getContext,a.getContext=function(d,e){e=a.$e(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Qd(c,b):0},Qd=(a,b)=>{var c=Pd(Kd),d={handle:c,attributes:b,version:b.Ig,xf:a};a.canvas&&(a.canvas.Ff=d);Kd[c]=d;("undefined"==typeof b.fh||b.fh)&&Sd(d);return c},Ud=a=>{Td=Kd[a];h.rf=V=Td&&Td.xf},Sd=a=>{a||=Td;if(!a.lh){a.lh=!0;var b=a.xf;Bd(b);Cd(b);Dd(b);b.uf=
b.getExtension("EXT_disjoint_timer_query");b.Rh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}};function Vd(){var a=V.getSupportedExtensions()||[];return a=a.concat(a.map(b=>"GL_"+b))}
var Wd={},Od,Td,Xd=a=>{var b=gb(a)+1,c=C(b);c&&D(a,q,c,b);return c},$d=[],ae=(a,b)=>{$d.length=0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;$d.push(112==c?w[b>>2]:105==c?t[b>>2]:y[b>>3]);b+=d?8:4}return $d},de=a=>{var b=be();a=a();ce(b);return a},ee=0;function fe(){for(var a=ge.length-1;0<=a;--a)he(a);ge=[];ie=[]}var ie=[];
function je(a,b,c){function d(g,k){if(g.length!=k.length)return!1;for(var n in g)if(g[n]!=k[n])return!1;return!0}for(var e in ie){var f=ie[e];if(f.sg==a&&d(f.xg,c))return}ie.push({sg:a,Mg:b,xg:c});ie.sort((g,k)=>g.Mg<k.Mg)}function ke(a){for(var b=0;b<ie.length;++b)ie[b].sg==a&&(ie.splice(b,1),--b)}function le(){return navigator.userActivation?navigator.userActivation.isActive:ee&&me.Hf}function ne(){if(le())for(var a=0;a<ie.length;++a){var b=ie[a];ie.splice(a,1);--a;b.sg.apply(null,b.xg)}}
var ge=[];function he(a){var b=ge[a];b.target.removeEventListener(b.ef,b.gh,b.mf);ge.splice(a,1)}function oe(a){function b(d){++ee;me=a;ne();a.pf(d);ne();--ee}if(!a.target)return-4;if(a.nf)a.gh=b,a.target.addEventListener(a.ef,b,a.mf),ge.push(a),pe||(ua.push(fe),pe=!0);else for(var c=0;c<ge.length;++c)ge[c].target==a.target&&ge[c].ef==a.ef&&he(c--);return 0}function qe(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function re(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var se={},pe,me,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe={},Ge=[0,document,window],W=a=>{a=2<a?a?E(q,a):"":a;return Ge[a]||document.querySelector(a)},Ie=a=>{var b=gb(a)+1,c=He(b);D(a,q,c,b);return c},Je=a=>de(()=>{var b=He(8),c=b+4,d=Ie(a.id);if(d=W(d))t[b>>2]=d.width,t[c>>2]=d.height;return[t[b>>2],t[c>>2]]}),Ke=(a,b,c)=>{a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0},Le=(a,b,c)=>{a.Jh?de(()=>{var d=Ie(a.id);Ke(d,b,c)}):(a.width=b,a.height=c)},Me=a=>{function b(){document.fullscreenElement||
document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Le(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=k,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=v,a.style.paddingTop=r,a.style.paddingBottom=u,a.style.marginLeft=B,a.style.marginRight=F,a.style.marginTop=G,a.style.marginBottom=N,document.body.style.margin=
fa,document.documentElement.style.overflow=P,document.body.scroll=J,a.style.yf=ya,a.Ff&&a.Ff.xf.viewport(0,0,d,e),Fe.Tf&&X.apply(null,[Fe.Tf,37,0,Fe.yg]))}var c=Je(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,k=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,v=a.style.paddingRight,r=a.style.paddingTop,u=a.style.paddingBottom,B=a.style.marginLeft,F=a.style.marginRight,G=a.style.marginTop,N=a.style.marginBottom,fa=document.body.style.margin,P=document.documentElement.style.overflow,
J=document.body.scroll,ya=a.style.yf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Ne=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Oe=a=>0>Ge.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Pe=(a,b)=>{if(0!=b.rg||0!=b.jg){Me(a);var c=b.wh?innerWidth:screen.width,d=b.wh?innerHeight:screen.height,e=Oe(a),f=e.width;e=e.height;var g=Je(a),k=g[0];g=g[1];3==b.rg?(Ne(a,(d-e)/2,(c-f)/
2),c=f,d=e):2==b.rg&&(c*g<k*d?(f=g*c/k,Ne(a,(d-f)/2,0),d=f):(f=k*d/g,Ne(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.hh&&(a.style.yf="optimizeSpeed",a.style.yf="-moz-crisp-edges",a.style.yf="-o-crisp-edges",a.style.yf="-webkit-optimize-contrast",a.style.yf="optimize-contrast",a.style.yf="crisp-edges",a.style.yf="pixelated");f=2==b.jg?devicePixelRatio:
1;0!=b.jg&&(c=c*f|0,d=d*f|0,Le(a,c,d),a.Ff&&a.Ff.xf.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return re()?-3:-1;Fe=b;b.Tf&&X.apply(null,[b.Tf,37,0,b.yg]);return 0},Qe=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Re=(a,b)=>{y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)t[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];t[a+1296>>2]=b.connected;t[a+1300>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;D(b.id,q,a+1304,64);D(b.mapping,q,a+1368,64)},Se=[],Te=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=V[c](),g=f&&Pd(d);f?(f.name=g,d[g]=f):U(1282);t[b+4*e>>2]=g}},Ue=(a,b,c,d,e,f,g,k)=>{b=S[b];if(a=V[a](b,c))d=k&&D(a.name,
q,k,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},Ve=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;
default:U(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:m[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){U(1280);aa(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:U(1280);aa(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:m[b>>0]=d?1:0}}else U(1281)},We=(a,b,c)=>{if(c){a=V.uf.getQueryObjectEXT(Ld[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else U(1281)},Xe=(a,b,c)=>{if(c){a=V.uf.getQueryObjectEXT(Ld[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else U(1281)},Ye=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ze=a=>{var b=a.Pf,c=a.Rg,d;if(!b)for(a.Pf=
b={},a.Qg={},d=0;d<V.getProgramParameter(a,35718);++d){var e=V.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Ye(f);g=0<g?f.slice(0,g):f;var k=a.tg;a.tg+=e;c[g]=[e,k];for(f=0;f<e;++f)b[k]=f,a.Qg[k++]=g}},Y=a=>{var b=V.Zg;if(b){var c=b.Pf[a];"number"==typeof c&&(b.Pf[a]=c=V.getUniformLocation(b,b.Qg[a]+(0<c?`[${c}]`:"")));return c}U(1282)},$e=(a,b,c,d)=>{if(c)if(a=S[a],Ze(a),a=V.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=
0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else U(1281)},af=(a,b,c,d)=>{if(c)if(a=V.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:t[c+4*b>>2]=Math.fround(a[b])}else U(1281)},bf=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?t:6==a?x:
5==a||28922==a?w:qa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Nd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},cf=[],df=[],ef=(a,b)=>{if(!re())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?le()?Pe(a,b):b.dh?(je(Pe,1,[a,b]),1):-2:-3:-4},ff=(a,b)=>{var c={target:W(2),ef:"beforeunload",nf:b,pf:(d=event)=>{var e=X.apply(null,[b,28,0,a]);e&&=e?E(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},mf:!0};return oe(c)},gf=(a,b,
c,d,e,f)=>{ue||=C(256);a={target:W(a),ef:f,nf:d,pf:(g=event)=>{var k=g.target.id?g.target.id:"",n=ue;D(qe(g.target),q,n+0,128);D(k,q,n+128,128);X.apply(null,[d,e,n,b])&&g.preventDefault()},mf:c};return oe(a)},hf=(a,b,c,d,e)=>{we||=C(280);return oe({target:a,ef:e,nf:d,pf:(f=event)=>{var g=we,k=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!k;t[g>>2]=n;t[g+4>>2]=re();var p=n?k:ve,v=p&&p.id?p.id:"";D(qe(p),q,g+8,128);D(v,
q,g+136,128);t[g+264>>2]=p?p.clientWidth:0;t[g+268>>2]=p?p.clientHeight:0;t[g+272>>2]=screen.width;t[g+276>>2]=screen.height;n&&(ve=k);X.apply(null,[d,19,g,b])&&f.preventDefault()},mf:c})},jf=(a,b,c,d,e)=>{xe||=C(1432);b={target:W(2),Hf:!0,ef:e,nf:c,pf:(f=event)=>{var g=xe;Re(g,f.gamepad);X.apply(null,[c,d,g,a])&&f.preventDefault()},mf:b};return oe(b)},kf=(a,b,c,d,e,f)=>{ye||=C(176);a={target:W(a),Hf:!0,ef:f,nf:d,pf:g=>{var k=ye;y[k>>3]=g.timeStamp;var n=k>>2;t[n+2]=g.location;t[n+3]=g.ctrlKey;t[n+
4]=g.shiftKey;t[n+5]=g.altKey;t[n+6]=g.metaKey;t[n+7]=g.repeat;t[n+8]=g.charCode;t[n+9]=g.keyCode;t[n+10]=g.which;D(g.key||"",q,k+44,32);D(g.code||"",q,k+76,32);D(g.char||"",q,k+108,32);D(g.locale||"",q,k+140,32);X.apply(null,[d,e,k,b])&&g.preventDefault()},mf:c};return oe(a)},lf=(a,b,c)=>{y[a>>3]=b.timeStamp;a>>=2;t[a+2]=b.screenX;t[a+3]=b.screenY;t[a+4]=b.clientX;t[a+5]=b.clientY;t[a+6]=b.ctrlKey;t[a+7]=b.shiftKey;t[a+8]=b.altKey;t[a+9]=b.metaKey;pa[2*a+20]=b.button;pa[2*a+21]=b.buttons;t[a+11]=
b.movementX;t[a+12]=b.movementY;c=Oe(c);t[a+13]=b.clientX-c.left;t[a+14]=b.clientY-c.top},mf=(a,b,c,d,e,f)=>{ze||=C(72);a=W(a);return oe({target:a,Hf:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ef:f,nf:d,pf:(g=event)=>{lf(ze,g,a);X.apply(null,[d,e,ze,b])&&g.preventDefault()},mf:c})},nf=(a,b,c,d,e)=>{Ae||=C(260);return oe({target:a,ef:e,nf:d,pf:(f=event)=>{var g=Ae,k=document.pointerLockElement||document.$e||document.hg||document.If;t[g>>2]=!!k;var n=k&&k.id?k.id:"";D(qe(k),q,g+4,128);D(n,q,g+
132,128);X.apply(null,[d,20,g,b])&&f.preventDefault()},mf:c})},of=(a,b,c,d)=>{Be||=C(36);a=W(a);return oe({target:a,ef:"resize",nf:d,pf:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=Be;t[g>>2]=e.detail;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset;t[g+32>>2]=pageYOffset;X.apply(null,[d,10,g,b])&&e.preventDefault()}}},mf:c})},pf=(a,b,c,d,e,f)=>{Ce||=C(1696);a=W(a);return oe({target:a,
Hf:"touchstart"==f||"touchend"==f,ef:f,nf:d,pf:g=>{for(var k,n={},p=g.touches,v=0;v<p.length;++v)k=p[v],k.Fg=k.Lg=0,n[k.identifier]=k;for(v=0;v<g.changedTouches.length;++v)k=g.changedTouches[v],k.Fg=1,n[k.identifier]=k;for(v=0;v<g.targetTouches.length;++v)n[g.targetTouches[v].identifier].Lg=1;p=Ce;y[p>>3]=g.timeStamp;var r=p>>2;t[r+3]=g.ctrlKey;t[r+4]=g.shiftKey;t[r+5]=g.altKey;t[r+6]=g.metaKey;r+=7;var u=Oe(a),B=0;for(v in n)if(k=n[v],t[r]=k.identifier,t[r+1]=k.screenX,t[r+2]=k.screenY,t[r+3]=k.clientX,
t[r+4]=k.clientY,t[r+5]=k.pageX,t[r+6]=k.pageY,t[r+7]=k.Fg,t[r+8]=k.Lg,t[r+9]=k.clientX-u.left,t[r+10]=k.clientY-u.top,r+=13,31<++B)break;t[p+8>>2]=B;X.apply(null,[d,e,p,b])&&g.preventDefault()},mf:c})},qf=(a,b,c)=>{var d=Ge[1];De||=C(8);return oe({target:d,ef:"visibilitychange",nf:c,pf:(e=event)=>{var f=De,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);t[f>>2]=document.hidden;t[f+4>>2]=g;X.apply(null,[c,21,f,a])&&e.preventDefault()},mf:b})},rf=(a,b,c,d)=>{Ee||=C(104);
return oe({target:a,Hf:!0,ef:"wheel",nf:d,pf:(e=event)=>{var f=Ee;lf(f,e,a);y[f+72>>3]=e.deltaX;y[f+80>>3]=e.deltaY;y[f+88>>3]=e.deltaZ;t[f+96>>2]=e.deltaMode;X.apply(null,[d,9,f,b])&&e.preventDefault()},mf:c})},sf={},uf=()=>{if(!tf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in sf)void 0===sf[b]?delete a[b]:a[b]=sf[b];
var c=[];for(b in a)c.push(`${b}=${a[b]}`);tf=c}return tf},tf,vf=a=>{try{a()}catch(b){l(b)}};function wf(){var a=Z,b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){xf.push(d);try{return e.apply(null,arguments)}finally{na||(xf.pop()===d||l(),yf&&1===zf&&0===xf.length&&(zf=0,vf(Af),"undefined"!=typeof Fibers&&Fibers.Vh()))}}:e})(c);return b}var zf=0,yf=null,Bf=0,xf=[],Cf={},Df={},Ef=0,Ff=null,Gf=[];
function Hf(){var a=C(4108),b=a+12;w[a>>2]=b;w[a+4>>2]=b+4096;b=xf[0];var c=Cf[b];void 0===c&&(c=Ef++,Cf[b]=c,Df[c]=b);t[a+8>>2]=c;return a}
function If(a){if(!na){if(0===zf){var b=!1,c=!1;a((d=0)=>{if(!na&&(Bf=d,b=!0,c)){zf=2;vf(()=>Jf(yf));"undefined"!=typeof wb&&tc&&Oc();d=!1;try{var e=(0,Z[Df[t[yf+8>>2]]])()}catch(k){e=k,d=!0}var f=!1;if(!yf){var g=Ff;g&&(Ff=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(zf=1,yf=Hf(),"undefined"!=typeof wb&&tc&&Nc(),vf(()=>Kf(yf)))}else 2===zf?(zf=0,vf(Lf),Mf(yf),yf=null,Gf.forEach(d=>Hc(d))):l(`invalid state: ${zf}`);return Bf}}
function Nb(a,b,c,d){a||=this;this.parent=a;this.vf=a.vf;this.Df=null;this.id=Fb++;this.name=b;this.mode=c;this.Re={};this.Te={};this.Mf=d}Object.defineProperties(Nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},qh:{get:function(){return K(this.mode)}},Gg:{get:function(){return 8192===(this.mode&61440)}}});gc();Gb=Array(4096);
Vb(I,"/");Xb("/tmp");Xb("/home");Xb("/home/web_user");(function(){Xb("/dev");lb(259,{read:()=>0,write:(d,e,f,g)=>g});Yb("/dev/null",259);jb(1280,nb);jb(1536,ob);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=cb(a).byteLength);return a[--b]};kc("/dev","random",c);kc("/dev","urandom",c);Xb("/dev/shm");Xb("/dev/shm/tmp")})();
(function(){Xb("/proc");var a=Xb("/proc/self");Xb("/proc/self/fd");Vb({vf(){var b=rb(a,"fd",16895,73);b.Re={Lf(c,d){var e=Sb(+d);c={parent:null,vf:{Jg:"fake"},Re:{Nf:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=ic;h.FS_createDataFile=zb;h.FS_createPreloadedFile=Ab;h.FS_unlink=$b;h.FS_createLazyFile=mc;h.FS_createDevice=kc;
h.requestFullscreen=function(a,b){function c(){Pc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Xc,Vc&&d.requestPointerLock(),Pc=!0,Wc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=w[SDL.screen>>2]|8388608),ad(h.canvas),$c()):ad(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Wc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),ad(h.canvas),$c()):ad(d));if(h.onFullScreen)h.onFullScreen(Pc);if(h.onFullscreen)h.onFullscreen(Pc)}Vc=a;Wc=b;"undefined"==typeof Vc&&(Vc=!0);"undefined"==typeof Wc&&(Wc=!1);var d=h.canvas;Uc||(Uc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,
d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=zc;h.setCanvasSize=function(a,b,c){ad(h.canvas,a,b);c||$c()};h.pauseMainLoop=Nc;h.resumeMainLoop=Oc;
h.getUserMedia=function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.rf&&a==h.canvas)return h.rf;var e;if(b){var f={antialias:!1,alpha:!1,Ig:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Wd&&(e=Rd(a,f)))var k=Kd[e].xf}else k=a.getContext("2d");if(!k)return null;c&&(b||"undefined"==typeof V||l("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.rf=k,b&&Ud(e),h.yh=b,Rc.forEach(n=>n()),xb());return k};for(var V,Nf=0;32>Nf;++Nf)Se.push(Array(Nf));var Of=new Float32Array(288);
for(Nf=0;288>Nf;++Nf)cf[Nf]=Of.subarray(0,Nf+1);var Pf=new Int32Array(288);for(Nf=0;288>Nf;++Nf)df[Nf]=Pf.subarray(0,Nf+1);
var Rf={Td:(a,b,c)=>{(new Va(a)).$e(b,c);Wa=a;Xa++;throw Wa;},_:function(a,b,c){pc=c;try{var d=Sb(a);switch(b){case 0:var e=qc();if(0>e)return-28;for(;Eb[e];)e++;return Tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=qc(),d.flags|=e,0;case 5:return e=qc(),pa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return t[Qf()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof nc||"ErrnoError"!==f.name)throw f;return-f.df}},Ya:function(a,b){try{if(0===
b)return-28;var c=gb("/")+1;if(b<c)return-68;D("/",q,a,b);return c}catch(d){if("undefined"==typeof nc||"ErrnoError"!==d.name)throw d;return-d.df}},Za:function(a,b,c){try{var d=Sb(a);if(!d.zf){var e=L(d.path,{Kf:!0}).node;if(!e.Re.ag)throw new H(54);var f=e.Re.ag(e);d.zf=f}a=0;for(var g=ec(d,0,1),k=Math.floor(g/280);k<d.zf.length&&a+280<=c;){var n=d.zf[k];if("."===n){var p=d.node.id;var v=4}else if(".."===n)p=L(d.path,{parent:!0}).node.id,v=4;else{var r=tb(d.node,n);p=r.id;v=8192===(r.mode&61440)?
2:K(r.mode)?4:40960===(r.mode&61440)?10:8}A=[p>>>0,(z=p,1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+a>>2]=A[0];t[b+a+4>>2]=A[1];A=[280*(k+1)>>>0,(z=280*(k+1),1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+a+8>>2]=A[0];t[b+a+12>>2]=A[1];pa[b+a+16>>1]=280;m[b+a+18>>0]=v;D(n,q,b+a+19,256);a+=280;k+=1}ec(d,280*k,0);return a}catch(u){if("undefined"==typeof nc||"ErrnoError"!==u.name)throw u;
return-u.df}},db:function(a,b,c){pc=c;try{var d=Sb(a);switch(b){case 21509:return d.Ve?0:-59;case 21505:if(!d.Ve)return-59;if(d.Ve.wf.nh){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=qc();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.Ve?0:-59;case 21506:case 21507:case 21508:if(!d.Ve)return-59;if(d.Ve.wf.oh)for(e=qc(),b=[],f=0;32>f;f++)b.push(m[e+f+17>>0]);
return 0;case 21519:if(!d.Ve)return-59;e=qc();return t[e>>2]=0;case 21520:return d.Ve?-28:-59;case 21531:e=qc();if(!d.Te.mh)throw new H(59);return d.Te.mh(d,b,e);case 21523:if(!d.Ve)return-59;d.Ve.wf.ph&&(f=[24,80],e=qc(),pa[e>>1]=f[0],pa[e+2>>1]=f[1]);return 0;case 21524:return d.Ve?0:-59;case 21515:return d.Ve?0:-59;default:return-28}}catch(g){if("undefined"==typeof nc||"ErrnoError"!==g.name)throw g;return-g.df}},_a:function(a,b,c){try{return b=b?E(q,b):"",b=oc(a,b),b=Za(b),"/"===b[b.length-1]&&
(b=b.substr(0,b.length-1)),Xb(b,c),0}catch(d){if("undefined"==typeof nc||"ErrnoError"!==d.name)throw d;return-d.df}},$:function(a,b,c,d){pc=d;try{b=b?E(q,b):"";b=oc(a,b);var e=d?qc():0;return bc(b,c,e).fd}catch(f){if("undefined"==typeof nc||"ErrnoError"!==f.name)throw f;return-f.df}},Xa:function(a,b,c,d){try{b=b?E(q,b):"";b=oc(a,b);if(0>=d)return-28;var e=Ib(b),f=Math.min(d,gb(e)),g=m[c+f];D(e,q,c,d+1);m[c+f]=g;return f}catch(k){if("undefined"==typeof nc||"ErrnoError"!==k.name)throw k;return-k.df}},
Wa:function(a,b){try{a=a?E(q,a):"";a:{try{var c=L(a,{Kf:!0}).node;if(!c)throw new H(44);if(!c.Re.sf)throw new H(63);var d=c.Re.sf(c)}catch(n){if(n&&n.node&&Za(a)!==Za(Jb(n.node))){var e=-54;break a}throw n;}t[b>>2]=d.eh;t[b+4>>2]=d.mode;w[b+8>>2]=d.th;t[b+12>>2]=d.uid;t[b+16>>2]=d.ih;t[b+20>>2]=d.Mf;A=[d.size>>>0,(z=d.size,1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+24>>2]=A[0];t[b+28>>2]=A[1];t[b+32>>2]=4096;t[b+36>>2]=d.Wg;var f=d.Ug.getTime(),
g=d.sh.getTime(),k=d.Xg.getTime();A=[Math.floor(f/1E3)>>>0,(z=Math.floor(f/1E3),1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+40>>2]=A[0];t[b+44>>2]=A[1];w[b+48>>2]=f%1E3*1E3;A=[Math.floor(g/1E3)>>>0,(z=Math.floor(g/1E3),1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+56>>2]=A[0];t[b+60>>2]=A[1];w[b+64>>2]=g%1E3*1E3;A=[Math.floor(k/1E3)>>>0,(z=Math.floor(k/1E3),1<=+Math.abs(z)?0<z?+Math.floor(z/
4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+72>>2]=A[0];t[b+76>>2]=A[1];w[b+80>>2]=k%1E3*1E3;A=[d.Eg>>>0,(z=d.Eg,1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[b+88>>2]=A[0];t[b+92>>2]=A[1];e=0}return e}catch(n){if("undefined"==typeof nc||"ErrnoError"!==n.name)throw n;return-n.df}},Va:function(a,b,c){try{b=b?E(q,b):"";b=oc(a,b);if(0===c)$b(b);else if(512===c){a=b;var d=L(a,{parent:!0}).node,e=ab(a),f=tb(d,e),g=Qb(d,e,!0);
if(g)throw new H(g);if(!d.Re.cg)throw new H(63);if(f.Df)throw new H(10);d.Re.cg(d,e);Lb(f)}else l("Invalid flags passed to unlinkat");return 0}catch(k){if("undefined"==typeof nc||"ErrnoError"!==k.name)throw k;return-k.df}},eb:()=>1,u:()=>{l("")},n:(a,b,c,d,e)=>{if(M)if(a=O[a])if(0>=e)M.ce=40963;else{var f=null;try{switch(b){case 4352:if(0<d){f=M.hf.createBuffer(1,d,e);for(var g=f.getChannelData(0),k=0;k<d;++k)g[k]=.0078125*q[c++]-1}a.jf=1;a.channels=1;a.length=d;break;case 4353:if(0<d)for(f=M.hf.createBuffer(1,
d>>1,e),g=f.getChannelData(0),c>>=1,k=0;k<d>>1;++k)g[k]=3.0517578125E-5*pa[c++];a.jf=2;a.channels=1;a.length=d>>1;break;case 4354:if(0<d){f=M.hf.createBuffer(2,d>>1,e);g=f.getChannelData(0);var n=f.getChannelData(1);for(k=0;k<d>>1;++k)g[k]=.0078125*q[c++]-1,n[k]=.0078125*q[c++]-1}a.jf=1;a.channels=2;a.length=d>>1;break;case 4355:if(0<d)for(f=M.hf.createBuffer(2,d>>2,e),g=f.getChannelData(0),n=f.getChannelData(1),c>>=1,k=0;k<d>>2;++k)g[k]=3.0517578125E-5*pa[c++],n[k]=3.0517578125E-5*pa[c++];a.jf=2;
a.channels=2;a.length=d>>2;break;case 65552:if(0<d)for(f=M.hf.createBuffer(1,d>>2,e),g=f.getChannelData(0),c>>=2,k=0;k<d>>2;++k)g[k]=x[c++];a.jf=4;a.channels=1;a.length=d>>2;break;case 65553:if(0<d)for(f=M.hf.createBuffer(2,d>>3,e),g=f.getChannelData(0),n=f.getChannelData(1),c>>=2,k=0;k<d>>3;++k)g[k]=x[c++],n[k]=x[c++];a.jf=4;a.channels=2;a.length=d>>3;break;default:M.ce=40963;return}a.frequency=e;a.We=f}catch(p){M.ce=40963}}else M.ce=40963},o:(a,b)=>{if(M){for(var c=0;c<a;++c){var d=t[b+4*c>>2];
if(0!==d){if(!O[d]){M.ce=40961;return}if(O[d].Bf){M.ce=40964;return}}}for(c=0;c<a;++c)d=t[b+4*c>>2],0!==d&&(bd[O[d].deviceId]--,delete O[d],ed.push(d))}},g:(a,b)=>{if(M){for(var c=0;c<a;++c){var d=t[b+4*c>>2];if(!M.sources[d]){M.ce=40961;return}}for(c=0;c<a;++c)d=t[b+4*c>>2],hd(M.sources[d],4116),ud(d,4105,0),delete M.sources[d],ed.push(d)}},F:(a,b)=>{if(M)for(var c=0;c<a;++c){var d={deviceId:M.deviceId,id:0<ed.length?ed.pop():dd++,Bf:0,We:null,frequency:0,jf:2,channels:1,length:0};bd[d.deviceId]++;
O[d.id]=d;t[b+4*c>>2]=d.id}},j:(a,b)=>{if(M)for(var c=0;c<a;++c){var d=M.hf.createGain();d.connect(M.gain);d={context:M,id:0<ed.length?ed.pop():dd++,type:4144,state:4113,Wd:[O[0]],Ze:[],kf:!1,pitch:1,Jf:1,gain:d,ng:0,mg:1,Xe:null,Ue:0,cf:Number.NEGATIVE_INFINITY,bf:0,bg:!1,refDistance:1,maxDistance:3.40282E38,rolloffFactor:1,position:[0,0,0],qf:[0,0,0],direction:[0,0,0],coneOuterGain:0,coneInnerAngle:360,coneOuterAngle:360,distanceModel:53250,eg:2,get playbackRate(){return this.pitch*this.Jf}};M.sources[d.id]=
d;t[b+4*c>>2]=d.id}},e:()=>{if(!M)return 40964;var a=M.ce;M.ce=0;return a},a:(a,b,c)=>{a=td(a,b);if(null!==a)if(c)switch(b){case 514:case 4097:case 4098:case 4103:case 4105:case 4112:case 4117:case 4118:case 4128:case 4129:case 4131:case 4132:case 4133:case 4134:case 4135:case 4628:case 8201:case 8202:case 53248:t[c>>2]=a;break;default:M.ce=40962}else M.ce=40963},i:a=>M&&M.sources[a]?!0:!1,hb:a=>{M&&((a=M.sources[a])?hd(a,4115):M.ce=40961)},x:a=>{M&&((a=M.sources[a])?hd(a,4114):M.ce=40961)},r:(a,
b,c)=>{if(M)if(a=M.sources[a],!a)M.ce=40961;else if(4136===a.type)M.ce=40964;else if(0!==b){for(var d=O[0],e=0;e<a.Wd.length;e++)if(0!==a.Wd[e].id){d=a.Wd[e];break}for(e=0;e<b;++e){var f=t[c+4*e>>2];f=O[f];if(!f){M.ce=40961;return}0===d.id||f.frequency===d.frequency&&f.jf===d.jf&&f.channels===d.channels||(M.ce=40964)}1===a.Wd.length&&0===a.Wd[0].id&&(a.Wd.length=0);a.type=4137;for(e=0;e<b;++e)f=t[c+4*e>>2],f=O[f],f.Bf++,a.Wd.push(f);a.kf&&kd(a);od(a);gd(a)}},p:a=>{M&&((a=M.sources[a])?hd(a,4116):
M.ce=40961)},h:(a,b,c)=>{if(M)if(a=M.sources[a],!a)M.ce=40961;else if(b>(1===a.Wd.length&&0===a.Wd[0].id?0:a.Ue))M.ce=40963;else if(0!==b){for(var d=0;d<b;d++){var e=a.Wd.shift();e.Bf--;t[c+4*d>>2]=e.id;a.Ue--}0===a.Wd.length&&a.Wd.push(O[0]);od(a);gd(a)}},c:(a,b,c)=>{switch(b){case 4097:case 4098:case 4099:case 4106:case 4109:case 4110:case 4128:case 4129:case 4130:case 4131:case 4132:case 4133:case 4134:case 8203:ud(a,b,c);break;default:ud(a,b,null)}},aa:a=>{if(!(a in bd)||0<bd[a])return 0;delete bd[a];
ed.push(a);return 1},dd:(a,b)=>{if(!(a in bd))return 0;var c=null,d=[],e=null;if(b>>=2)for(var f=0,g=0;;){f=t[b++];d.push(f);if(0===f)break;g=t[b++];d.push(g);switch(f){case 4103:c||={};c.sampleRate=g;break;case 4112:case 4113:break;case 6546:switch(g){case 0:e=!1;break;case 1:e=!0;break;case 2:break;default:return 0}break;case 6550:if(0!==g)return 0;break;default:return 0}}f=window.AudioContext||window.webkitAudioContext;b=null;try{b=c?new f(c):new f}catch(p){return 0}La(b);"undefined"==typeof b.createGain&&
(b.createGain=b.createGainNode);c=b.createGain();c.connect(b.destination);var k={deviceId:a,id:0<ed.length?ed.pop():dd++,Ch:d,hf:b,listener:{position:[0,0,0],qf:[0,0,0],direction:[0,0,0],ug:[0,0,0]},sources:[],interval:setInterval(()=>{var p=k;if(1!==rc||"visible"==document.visibilityState)for(var v in p.sources)gd(p.sources[v])},25),gain:c,distanceModel:53250,speedOfSound:343.3,dopplerFactor:1,Pg:!1,Dg:e||!1,ig:0,get ce(){return this.ig},set ce(p){if(0===this.ig||0===p)this.ig=p}};bd[a]++;cd[k.id]=
k;if(null!==e)for(var n in cd)d=cd[n],d.deviceId===a&&(d.Dg=e,pd(d));return k.id},Nb:a=>{var b=cd[a];M!==b&&(cd[a].interval&&clearInterval(cd[a].interval),bd[b.deviceId]--,delete cd[a],ed.push(a))},Yb:a=>a in cd?cd[a].deviceId:0,ba:a=>{0===a?M=null:M=cd[a];return 1},od:a=>a&&"Emscripten OpenAL"!==(a?E(q,a):"")?0:"undefined"!=typeof AudioContext||"undefined"!=typeof webkitAudioContext?(a=0<ed.length?ed.pop():dd++,bd[a]=0,a):0,ca:()=>{},Cb:()=>{},Na:a=>{if(12448==a)return Q=12288,1;Q=12300;return 0},
Qa:(a,b,c,d,e)=>{if(62E3!=a)Q=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)R.alpha=0<t[b+4>>2];else if(12325==a)R.depth=0<t[b+4>>2];else if(12326==a)R.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],R.antialias=0<a;else if(12338==a)a=t[b+4>>2],R.antialias=1==a;else if(12544==a)R.Ph=12547!=t[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(t[e>>2]=1),c&&0<d&&(w[c>>2]=62002),Q=12288,c=1):(Q=12300,c=0)}return c},Ea:(a,b,c,d)=>{if(62E3!=a)return Q=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+
4>>2];else if(12344==b)break;else return Q=12292,0;d+=8}if(2!=a)return Q=12293,0;R.Ig=a-1;R.Qh=0;Ad=Rd(h.canvas,R);if(0!=Ad)return Q=12288,Ud(Ad),h.yh=!0,Rc.forEach(function(e){e()}),Ud(null),62004;Q=12297;return 0},Ga:(a,b)=>{if(62E3!=a)return Q=12296,0;if(62002!=b)return Q=12293,0;Q=12288;return 62006},Fa:(a,b)=>{if(62E3!=a)return Q=12296,0;if(62004!=b)return Q=12294,0;a=Ad;Td===Kd[a]&&(Td=null);if("object"==typeof se)for(var c=Kd[a].xf.canvas,d=0;d<ge.length;++d)ge[d].target!=c||he(d--);Kd[a]&&
Kd[a].xf.canvas&&(Kd[a].xf.canvas.Ff=void 0);Kd[a]=null;Q=12288;wd==b&&(wd=0);return 1},Ha:(a,b)=>{if(62E3!=a)return Q=12296,0;if(62006!=b)return Q=12301,1;xd==b&&(xd=0);yd==b&&(yd=0);Q=12288;return 1},Ra:(a,b,c,d)=>{if(62E3!=a)return Q=12296,0;if(62002!=b)return Q=12293,0;if(!d)return Q=12300,0;Q=12288;switch(c){case 12320:return t[d>>2]=R.alpha?32:24,1;case 12321:return t[d>>2]=R.alpha?8:0,1;case 12322:return t[d>>2]=8,1;case 12323:return t[d>>2]=8,1;case 12324:return t[d>>2]=8,1;case 12325:return t[d>>
2]=R.depth?24:0,1;case 12326:return t[d>>2]=R.stencil?8:0,1;case 12327:return t[d>>2]=12344,1;case 12328:return t[d>>2]=62002,1;case 12329:return t[d>>2]=0,1;case 12330:return t[d>>2]=4096,1;case 12331:return t[d>>2]=16777216,1;case 12332:return t[d>>2]=4096,1;case 12333:return t[d>>2]=0,1;case 12334:return t[d>>2]=0,1;case 12335:return t[d>>2]=12344,1;case 12337:return t[d>>2]=R.antialias?4:0,1;case 12338:return t[d>>2]=R.antialias?1:0,1;case 12339:return t[d>>2]=4,1;case 12340:return t[d>>2]=12344,
1;case 12341:case 12342:case 12343:return t[d>>2]=-1,1;case 12345:case 12346:return t[d>>2]=0,1;case 12347:return t[d>>2]=0,1;case 12348:return t[d>>2]=1;case 12349:case 12350:return t[d>>2]=0,1;case 12351:return t[d>>2]=12430,1;case 12352:return t[d>>2]=4,1;case 12354:return t[d>>2]=0,1;default:return Q=12292,0}},U:a=>{Q=12288;return 0!=a&&1!=a?0:62E3},Da:()=>Q,Oa:(a,b,c)=>{if(62E3!=a)return Q=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);vd=!0;Q=12288;return 1},Ia:(a,b,c,d)=>{if(62E3!=a)return Q=12296,
0;if(0!=d&&62004!=d)return Q=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return Q=12301,0;Ud(d?Ad:null);wd=d;yd=b;xd=c;Q=12288;return 1},Ca:(a,b)=>{if(62E3!=a)return Q=12296,0;Q=12288;if(zd[b])return zd[b];switch(b){case 12371:a=Xd("Emscripten");break;case 12372:a=Xd("1.4 Emscripten EGL");break;case 12373:a=Xd("");break;case 12429:a=Xd("OpenGL_ES");break;default:return Q=12300,0}return zd[b]=a},Ja:()=>{if(vd)if(h.rf)if(h.rf.isContextLost())Q=12302;else return Q=12288,1;else Q=12290;else Q=12289;return 0},
Ka:(a,b)=>{if(62E3!=a)return Q=12296,0;0==b?Bc(0,0):Bc(1,b);Q=12288;return 1},Pa:a=>{if(62E3!=a)return Q=12296,0;yd=xd=wd=0;vd=!1;Q=12288;return 1},Ma:()=>{Q=12288;return 1},La:()=>{Q=12288;return 1},cb:(a,b,c)=>{b=ae(b,c);return Oa[a].apply(null,b)},b:(a,b,c)=>{b=ae(b,c);return Oa[a].apply(null,b)},w:()=>Date.now(),xa:()=>{if(!re())return-1;ke(Pe);var a=Ge[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();
else return-1;return 0},Aa:()=>{ke(Qe);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},m:()=>devicePixelRatio,f:(a,b,c)=>{a=W(a);if(!a)return-4;a=Oe(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},X:(a,b)=>{if(0>a||a>=te.length)return-5;if(!te[a])return-7;Re(b,te[a]);return 0},v:xc,Sa:()=>te.length,Ba:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},da:function(a){V.activeTexture(a)},Sd:(a,b)=>{V.attachShader(S[a],T[b])},ta:(a,b)=>{V.uf.beginQueryEXT(a,Ld[b])},Rd:(a,
b,c)=>{V.bindAttribLocation(S[a],b,c?E(q,c):"")},Qd:(a,b)=>{V.bindBuffer(a,Fd[b])},Pd:(a,b)=>{V.bindFramebuffer(a,Gd[b])},Od:(a,b)=>{V.bindRenderbuffer(a,Hd[b])},Nd:(a,b)=>{V.bindTexture(a,Id[b])},la:a=>{V.bindVertexArray(Jd[a])},Md:function(a,b,c,d){V.blendColor(a,b,c,d)},Ld:function(a){V.blendEquation(a)},Kd:function(a,b){V.blendEquationSeparate(a,b)},Jd:function(a,b){V.blendFunc(a,b)},Id:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Hd:(a,b,c,d)=>{V.bufferData(a,c?q.subarray(c,c+b):b,d)},Gd:(a,
b,c,d)=>{V.bufferSubData(a,b,q.subarray(d,d+c))},Fd:function(a){return V.checkFramebufferStatus(a)},Ed:function(a){V.clear(a)},Dd:function(a,b,c,d){V.clearColor(a,b,c,d)},Cd:function(a){V.clearDepth(a)},Bd:function(a){V.clearStencil(a)},Ad:(a,b,c,d)=>{V.colorMask(!!a,!!b,!!c,!!d)},zd:a=>{V.compileShader(T[a])},yd:(a,b,c,d,e,f,g,k)=>{V.compressedTexImage2D(a,b,c,d,e,f,k?q.subarray(k,k+g):null)},xd:(a,b,c,d,e,f,g,k,n)=>{V.compressedTexSubImage2D(a,b,c,d,e,f,g,n?q.subarray(n,n+k):null)},wd:function(a,
b,c,d,e,f,g,k){V.copyTexImage2D(a,b,c,d,e,f,g,k)},vd:function(a,b,c,d,e,f,g,k){V.copyTexSubImage2D(a,b,c,d,e,f,g,k)},ud:()=>{var a=Pd(S),b=V.createProgram();b.name=a;b.Xf=b.Vf=b.Wf=0;b.tg=1;S[a]=b;return a},td:a=>{var b=Pd(T);T[b]=V.createShader(a);return b},sd:function(a){V.cullFace(a)},rd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Fd[d];e&&(V.deleteBuffer(e),e.name=0,Fd[d]=null)}},qd:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Gd[d];e&&(V.deleteFramebuffer(e),e.name=0,Gd[d]=null)}},pd:a=>
{if(a){var b=S[a];b?(V.deleteProgram(b),b.name=0,S[a]=null):U(1281)}},va:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Ld[d];e&&(V.uf.deleteQueryEXT(e),Ld[d]=null)}},nd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Hd[d];e&&(V.deleteRenderbuffer(e),e.name=0,Hd[d]=null)}},md:a=>{if(a){var b=T[a];b?(V.deleteShader(b),T[a]=null):U(1281)}},ld:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Id[d];e&&(V.deleteTexture(e),e.name=0,Id[d]=null)}},ka:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];V.deleteVertexArray(Jd[d]);
Jd[d]=null}},kd:function(a){V.depthFunc(a)},jd:a=>{V.depthMask(!!a)},id:function(a,b){V.depthRange(a,b)},hd:(a,b)=>{V.detachShader(S[a],T[b])},gd:function(a){V.disable(a)},fd:a=>{V.disableVertexAttribArray(a)},ed:(a,b,c)=>{V.drawArrays(a,b,c)},ga:(a,b,c,d)=>{V.drawArraysInstanced(a,b,c,d)},ha:(a,b)=>{for(var c=Se[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];V.drawBuffers(c)},cd:(a,b,c,d)=>{V.drawElements(a,b,c,d)},fa:(a,b,c,d,e)=>{V.drawElementsInstanced(a,b,c,d,e)},bd:function(a){V.enable(a)},ad:a=>{V.enableVertexAttribArray(a)},
sa:a=>{V.uf.endQueryEXT(a)},$c:function(){V.finish()},_c:function(){V.flush()},Zc:(a,b,c,d)=>{V.framebufferRenderbuffer(a,b,c,Hd[d])},Yc:(a,b,c,d,e)=>{V.framebufferTexture2D(a,b,c,Id[d],e)},Xc:function(a){V.frontFace(a)},Wc:(a,b)=>{Te(a,b,"createBuffer",Fd)},Uc:(a,b)=>{Te(a,b,"createFramebuffer",Gd)},wa:(a,b)=>{for(var c=0;c<a;c++){var d=V.uf.createQueryEXT();if(!d){for(U(1282);c<a;)t[b+4*c++>>2]=0;break}var e=Pd(Ld);d.name=e;Ld[e]=d;t[b+4*c>>2]=e}},Tc:(a,b)=>{Te(a,b,"createRenderbuffer",Hd)},Sc:(a,
b)=>{Te(a,b,"createTexture",Id)},ja:function(a,b){Te(a,b,"createVertexArray",Jd)},Vc:function(a){V.generateMipmap(a)},Rc:(a,b,c,d,e,f,g)=>{Ue("getActiveAttrib",a,b,c,d,e,f,g)},Qc:(a,b,c,d,e,f,g)=>{Ue("getActiveUniform",a,b,c,d,e,f,g)},Pc:(a,b,c,d)=>{a=V.getAttachedShaders(S[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=T.indexOf(a[b])},Oc:(a,b)=>V.getAttribLocation(S[a],b?E(q,b):""),Nc:(a,b)=>Ve(a,b,4),Mc:(a,b,c)=>{c?t[c>>2]=V.getBufferParameter(a,b):U(1281)},Lc:()=>{var a=V.getError()||
Od;Od=0;return a},Kc:(a,b)=>Ve(a,b,2),Jc:(a,b,c,d)=>{a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Ic:(a,b)=>Ve(a,b,0),Gc:(a,b,c,d)=>{a=V.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,q,d,b):0;c&&(t[c>>2]=b)},Hc:(a,b,c)=>{if(c)if(a>=Ed)U(1281);else if(a=S[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.Xf)for(b=0;b<V.getProgramParameter(a,
35718);++b)a.Xf=Math.max(a.Xf,V.getActiveUniform(a,b).name.length+1);t[c>>2]=a.Xf}else if(35722==b){if(!a.Vf)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Vf=Math.max(a.Vf,V.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Vf}else if(35381==b){if(!a.Wf)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Wf=Math.max(a.Wf,V.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Wf}else t[c>>2]=V.getProgramParameter(a,b);else U(1281)},na:We,pa:Xe,ma:We,oa:Xe,qa:(a,b,c)=>{c?t[c>>2]=V.uf.getQueryEXT(a,b):U(1281)},
Fc:(a,b,c)=>{c?t[c>>2]=V.getRenderbufferParameter(a,b):U(1281)},Dc:(a,b,c,d)=>{a=V.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,q,d,b):0;c&&(t[c>>2]=b)},Cc:(a,b,c,d)=>{a=V.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Bc:(a,b,c,d)=>{if(a=V.getShaderSource(T[a]))b=0<b&&d?D(a,q,d,b):0,c&&(t[c>>2]=b)},Ec:(a,b,c)=>{c?35716==b?(a=V.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(T[a]),
t[c>>2]=a?a.length+1:0):t[c>>2]=V.getShaderParameter(T[a],b):U(1281)},Ac:a=>{var b=Md[a];if(!b){switch(a){case 7939:b=Xd(Vd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||U(1280);b=b?Xd(b):0;break;case 7938:b=Xd(`OpenGL ES 2.0 (${V.getParameter(7938)})`);break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Xd(b);break;default:U(1280)}Md[a]=
b}return b},zc:(a,b,c)=>{c?x[c>>2]=V.getTexParameter(a,b):U(1281)},yc:(a,b,c)=>{c?t[c>>2]=V.getTexParameter(a,b):U(1281)},vc:(a,b)=>{b=b?E(q,b):"";if(a=S[a]){Ze(a);var c=a.Pf,d=0,e=b,f=Ye(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Rg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else U(1281);return-1},xc:(a,b,c)=>{$e(a,b,c,2)},wc:(a,b,c)=>{$e(a,b,c,0)},sc:(a,b,c)=>{c?t[c>>2]=V.getVertexAttribOffset(a,b):U(1281)},uc:(a,b,c)=>{af(a,b,c,2)},tc:(a,b,c)=>{af(a,
b,c,5)},rc:function(a,b){V.hint(a,b)},qc:a=>(a=Fd[a])?V.isBuffer(a):0,pc:function(a){return V.isEnabled(a)},oc:a=>(a=Gd[a])?V.isFramebuffer(a):0,nc:a=>(a=S[a])?V.isProgram(a):0,ua:a=>(a=Ld[a])?V.uf.isQueryEXT(a):0,mc:a=>(a=Hd[a])?V.isRenderbuffer(a):0,lc:a=>(a=T[a])?V.isShader(a):0,kc:a=>(a=Id[a])?V.isTexture(a):0,ia:a=>(a=Jd[a])?V.isVertexArray(a):0,jc:function(a){V.lineWidth(a)},ic:a=>{a=S[a];V.linkProgram(a);a.Pf=0;a.Rg={}},hc:(a,b)=>{3317==a&&(Nd=b);V.pixelStorei(a,b)},gc:function(a,b){V.polygonOffset(a,
b)},ra:(a,b)=>{V.uf.queryCounterEXT(Ld[a],b)},fc:(a,b,c,d,e,f,g)=>{(g=bf(f,e,c,d,g))?V.readPixels(a,b,c,d,e,f,g):U(1280)},ec:()=>{},dc:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},cc:(a,b)=>{V.sampleCoverage(a,!!b)},bc:function(a,b,c,d){V.scissor(a,b,c,d)},ac:()=>{U(1280)},$b:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?t[d+4*f>>2]:-1,k=t[c+4*f>>2];g=k?E(q,k,0>g?void 0:g):"";e+=g}V.shaderSource(T[a],e)},_b:function(a,b,c){V.stencilFunc(a,b,c)},Zb:function(a,b,c,d){V.stencilFuncSeparate(a,b,
c,d)},Xb:function(a){V.stencilMask(a)},Wb:function(a,b){V.stencilMaskSeparate(a,b)},Vb:function(a,b,c){V.stencilOp(a,b,c)},Ub:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Tb:(a,b,c,d,e,f,g,k,n)=>{V.texImage2D(a,b,c,d,e,f,g,k,n?bf(k,g,d,e,n):null)},Sb:function(a,b,c){V.texParameterf(a,b,c)},Rb:(a,b,c)=>{V.texParameterf(a,b,x[c>>2])},Qb:function(a,b,c){V.texParameteri(a,b,c)},Pb:(a,b,c)=>{V.texParameteri(a,b,t[c>>2])},Ob:(a,b,c,d,e,f,g,k,n)=>{var p=null;n&&(p=bf(k,g,e,f,n));V.texSubImage2D(a,b,c,
d,e,f,g,k,p)},Mb:(a,b)=>{V.uniform1f(Y(a),b)},Lb:(a,b,c)=>{if(288>=b)for(var d=cf[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);V.uniform1fv(Y(a),d)},Kb:(a,b)=>{V.uniform1i(Y(a),b)},Jb:(a,b,c)=>{if(288>=b)for(var d=df[b-1],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);V.uniform1iv(Y(a),d)},Ib:(a,b,c)=>{V.uniform2f(Y(a),b,c)},Hb:(a,b,c)=>{if(144>=b)for(var d=cf[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);V.uniform2fv(Y(a),
d)},Gb:(a,b,c)=>{V.uniform2i(Y(a),b,c)},Fb:(a,b,c)=>{if(144>=b)for(var d=df[2*b-1],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);V.uniform2iv(Y(a),d)},Eb:(a,b,c,d)=>{V.uniform3f(Y(a),b,c,d)},Db:(a,b,c)=>{if(96>=b)for(var d=cf[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);V.uniform3fv(Y(a),d)},Bb:(a,b,c,d)=>{V.uniform3i(Y(a),b,c,d)},Ab:(a,b,c)=>{if(96>=b)for(var d=df[3*b-1],e=0;e<3*b;e+=
3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);V.uniform3iv(Y(a),d)},zb:(a,b,c,d,e)=>{V.uniform4f(Y(a),b,c,d,e)},yb:(a,b,c)=>{if(72>=b){var d=cf[4*b-1],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);V.uniform4fv(Y(a),d)},xb:(a,b,c,d,e)=>{V.uniform4i(Y(a),b,c,d,e)},wb:(a,b,c)=>{if(72>=b)for(var d=df[4*b-1],e=0;e<4*b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+
2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2];else d=t.subarray(c>>2,c+16*b>>2);V.uniform4iv(Y(a),d)},vb:(a,b,c,d)=>{if(72>=b)for(var e=cf[4*b-1],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);V.uniformMatrix2fv(Y(a),!!c,e)},ub:(a,b,c,d)=>{if(32>=b)for(var e=cf[9*b-1],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>
2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);V.uniformMatrix3fv(Y(a),!!c,e)},tb:(a,b,c,d)=>{if(18>=b){var e=cf[16*b-1],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=x.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(Y(a),
!!c,e)},sb:a=>{a=S[a];V.useProgram(a);V.Zg=a},rb:a=>{V.validateProgram(S[a])},qb:function(a,b){V.vertexAttrib1f(a,b)},pb:(a,b)=>{V.vertexAttrib1f(a,x[b>>2])},ob:function(a,b,c){V.vertexAttrib2f(a,b,c)},nb:(a,b)=>{V.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},mb:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},lb:(a,b)=>{V.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},kb:function(a,b,c,d,e){V.vertexAttrib4f(a,b,c,d,e)},jb:(a,b)=>{V.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},ea:(a,b)=>{V.vertexAttribDivisor(a,
b)},ib:(a,b,c,d,e,f)=>{V.vertexAttribPointer(a,b,c,!!d,e,f)},gb:function(a,b,c,d){V.viewport(a,b,c,d)},t:()=>1,fb:(a,b,c)=>q.copyWithin(a,b,b+c),ya:(a,b,c)=>ef(a,{rg:t[c>>2],jg:t[c+4>>2],hh:t[c+8>>2],dh:b,Tf:t[c+12>>2],yg:t[c+16>>2]}),T:(a,b)=>{a=W(a);return a?a.requestPointerLock?le()?Qe(a):b?(je(Qe,2,[a]),1):-2:-1:-4},Ua:()=>{l("OOM")},Y:()=>(te=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1,y:(a,b,c)=>"undefined"==typeof onbeforeunload?
-1:1!==c?-5:ff(a,b),L:(a,b,c,d)=>gf(a,b,c,d,12,"blur"),l:Ke,s:(a,b,c)=>{a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},M:(a,b,c,d)=>gf(a,b,c,d,13,"focus"),B:(a,b,c,d)=>{if(!re())return-1;a=W(a);if(!a)return-4;hf(a,b,c,d,"webkitfullscreenchange");return hf(a,b,c,d,"fullscreenchange")},W:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?jf(a,b,c,26,"gamepadconnected"):-1,V:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?jf(a,b,c,27,"gamepaddisconnected"):
-1,E:(a,b,c,d)=>kf(a,b,c,d,2,"keydown"),C:(a,b,c,d)=>kf(a,b,c,d,1,"keypress"),D:(a,b,c,d)=>kf(a,b,c,d,3,"keyup"),R:(a,b,c,d)=>mf(a,b,c,d,5,"mousedown"),P:(a,b,c,d)=>mf(a,b,c,d,33,"mouseenter"),O:(a,b,c,d)=>mf(a,b,c,d,34,"mouseleave"),S:(a,b,c,d)=>mf(a,b,c,d,8,"mousemove"),Q:(a,b,c,d)=>mf(a,b,c,d,6,"mouseup"),G:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.$e||document.body.hg||document.body.If))return-1;a=W(a);if(!a)return-4;nf(a,b,c,d,"mozpointerlockchange");
nf(a,b,c,d,"webkitpointerlockchange");nf(a,b,c,d,"mspointerlockchange");return nf(a,b,c,d,"pointerlockchange")},A:(a,b,c,d)=>of(a,b,c,d),H:(a,b,c,d)=>pf(a,b,c,d,25,"touchcancel"),J:(a,b,c,d)=>pf(a,b,c,d,23,"touchend"),I:(a,b,c,d)=>pf(a,b,c,d,24,"touchmove"),K:(a,b,c,d)=>pf(a,b,c,d,22,"touchstart"),z:(a,b,c)=>qf(a,b,c),N:(a,b,c,d)=>(a=W(a))?"undefined"!=typeof a.onwheel?rf(a,b,c,d):-1:-4,za:a=>document.title=a?E(q,a):"",d:a=>If(b=>Mc(b,a)),$a:(a,b)=>{var c=0;uf().forEach((d,e)=>{var f=b+c;e=w[a+4*
e>>2]=f;for(f=0;f<d.length;++f)m[e++>>0]=d.charCodeAt(f);m[e>>0]=0;c+=d.length+1});return 0},ab:(a,b)=>{var c=uf();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},k:Lc,q:function(a){try{var b=Sb(a);dc(b);return 0}catch(c){if("undefined"==typeof nc||"ErrnoError"!==c.name)throw c;return c.df}},bb:function(a,b,c,d){try{a:{var e=Sb(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],n=w[a+4>>2];a+=8;var p=e,v=k,r=n,u=f,B=m;if(0>r||0>u)throw new H(28);if(null===p.fd)throw new H(8);if(1===
(p.flags&2097155))throw new H(8);if(K(p.node.mode))throw new H(31);if(!p.Te.read)throw new H(28);var F="undefined"!=typeof u;if(!F)u=p.position;else if(!p.seekable)throw new H(70);var G=p.Te.read(p,B,v,r,u);F||(p.position+=G);var N=G;if(0>N){var fa=-1;break a}b+=N;if(N<n)break;"undefined"!==typeof f&&(f+=N)}fa=b}w[d>>2]=fa;return 0}catch(P){if("undefined"==typeof nc||"ErrnoError"!==P.name)throw P;return P.df}},Ta:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;
var f=Sb(a);ec(f,b,d);A=[f.position>>>0,(z=f.position,1<=+Math.abs(z)?0<z?+Math.floor(z/4294967296)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];t[e>>2]=A[0];t[e+4>>2]=A[1];f.zf&&0===b&&0===d&&(f.zf=null);return 0}catch(g){if("undefined"==typeof nc||"ErrnoError"!==g.name)throw g;return g.df}},Z:function(a,b,c,d){try{a:{var e=Sb(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],n=w[a+4>>2];a+=8;var p=fc(e,m,k,n,f);if(0>p){var v=-1;break a}b+=p;"undefined"!==typeof f&&(f+=p)}v=b}w[d>>2]=v;return 0}catch(r){if("undefined"==
typeof nc||"ErrnoError"!==r.name)throw r;return r.df}}},Z=function(){function a(c){Z=c.exports;Z=wf();ma=Z.Ud;c=ma.buffer;h.HEAP8=m=new Int8Array(c);h.HEAP16=pa=new Int16Array(c);h.HEAPU8=q=new Uint8Array(c);h.HEAPU16=qa=new Uint16Array(c);h.HEAP32=t=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);h.HEAPF32=x=new Float32Array(c);h.HEAPF64=y=new Float64Array(c);sa.unshift(Z.Vd);Ca("wasm-instantiate");return Z}var b={a:Rf};Ba("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,
a)}catch(c){return aa(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ka(b,function(c){a(c.instance)});return{}}(),Mf=a=>(Mf=Z.Xd)(a),Sf=h._main=(a,b)=>(Sf=h._main=Z.Yd)(a,b),C=a=>(C=Z.Zd)(a),Qf=()=>(Qf=Z._d)(),be=()=>(be=Z.$d)(),ce=a=>(ce=Z.ae)(a),He=a=>(He=Z.be)(a),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=Z.de)(a,b,c);h.dynCall_ii=(a,b)=>(h.dynCall_ii=Z.ee)(a,b);var dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=Z.fe)(a,b);
h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=Z.ge)(a,b,c,d);var X=h.dynCall_iiii=(a,b,c,d)=>(X=h.dynCall_iiii=Z.he)(a,b,c,d);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=Z.ie)(a,b,c,d,e);var dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=Z.je)(a,b,c);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=Z.ke)(a,b,c,d,e);h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiiii=Z.le)(a,b,c,d,e,f,g);var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=Z.me)(a);
h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=Z.ne)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=Z.oe)(a,b,c,d,e,f,g);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=Z.pe)(a,b,c,d,e,f);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_viiiiiii=Z.qe)(a,b,c,d,e,f,g,k);h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,k,n,p,v)=>(h.dynCall_viiiiiiiiii=Z.re)(a,b,c,d,e,f,g,k,n,p,v);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_iiiiiiii=Z.se)(a,b,c,d,e,f,g,k);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,k,n,p)=>(h.dynCall_iiiiiiiiii=Z.te)(a,b,c,d,e,f,g,k,n,p);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,k,n,p,v,r,u,B,F,G)=>(h.dynCall_iiiiiiiiiiiiiiff=Z.ue)(a,b,c,d,e,f,g,k,n,p,v,r,u,B,F,G);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_iiiiiiiii=Z.ve)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,k,n,p,v,r)=>(h.dynCall_viiiiiiiiiii=Z.we)(a,b,c,d,e,f,g,k,n,p,v,r);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,k,n,p,v)=>(h.dynCall_iiiiiidiiff=Z.xe)(a,b,c,d,e,f,g,k,n,p,v);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.ye)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.ze)(a,b);h.dynCall_i=a=>(h.dynCall_i=Z.Ae)(a);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=Z.Be)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=Z.Ce)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_viiiiiiii=Z.De)(a,b,c,d,e,f,g,k,n);
h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,k,n,p)=>(h.dynCall_viiiiiiiii=Z.Ee)(a,b,c,d,e,f,g,k,n,p);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=Z.Fe)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=Z.Ge)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=Z.He)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=Z.Ie)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=Z.Je)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=Z.Ke)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=Z.Le)(a,b,c,d,e,f);
h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=Z.Me)(a,b,c,d,e,f,g);var Kf=a=>(Kf=Z.Ne)(a),Af=()=>(Af=Z.Oe)(),Jf=a=>(Jf=Z.Pe)(a),Lf=()=>(Lf=Z.Qe)();h.addRunDependency=Ba;h.removeRunDependency=Ca;h.FS_createPath=ic;h.FS_createLazyFile=mc;h.FS_createDevice=kc;h.FS_createPreloadedFile=Ab;h.FS_createDataFile=zb;h.FS_unlink=$b;var Tf;Aa=function Uf(){Tf||Vf();Tf||(Aa=Uf)};
function Wf(a=[]){var b=Sf;a.unshift(da);var c=a.length,d=He(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Ie(g);e+=4});w[e>>2]=0;try{var f=b(c,d);Lc(f,!0)}catch(g){Jc(g)}}
function Vf(){var a=ca;function b(){if(!Tf&&(Tf=!0,h.calledRun=!0,!na)){h.noFSInit||hc||(hc=!0,gc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?kc("/dev","stdin",h.stdin):Zb("/dev/tty","/dev/stdin"),h.stdout?kc("/dev","stdout",null,h.stdout):Zb("/dev/tty","/dev/stdout"),h.stderr?kc("/dev","stderr",null,h.stderr):Zb("/dev/tty1","/dev/stderr"),bc("/dev/stdin",0),bc("/dev/stdout",1),bc("/dev/stderr",1));Hb=!1;Ta(sa);Ta(ta);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Xf&&Wf(a);
if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();va.unshift(c)}Ta(va)}}if(!(0<xa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();Ta(ra);0<xa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Xf=!0;
h.noInitialRun&&(Xf=!1);Vf();
